/**
 * Image pipeline for the Nova Ventures website.
 *
 *   npm run images
 *
 * Reads the master photography from `assets/images-source/` and the logo files from
 * `assets/logos-source/`, and writes web-ready assets into `public/`:
 *
 *   public/images/<id>-{480,768,1024,1536}.webp   responsive WebP variants
 *   public/images/<id>-1536.jpg                  JPEG fallback (older browsers, e-mail clients)
 *   public/images/og-default.jpg                 1200x630 Open Graph / social share image
 *   public/logos/*                                optimised logo files + favicons / PWA icons
 *   src/data/imageManifest.ts                    generated manifest (dimensions + variants)
 *
 * Source variants preserve the original ratio; SiteImage uses object-cover in
 * consistent 3:2 business frames and supports fit=natural for uncropped artwork.
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const root = fileURLToPath(new URL('..', import.meta.url))
const srcDir = path.join(root, 'assets/images-source')
const logoSrcDir = path.join(root, 'assets/logos-source')
const outDir = path.join(root, 'public/images')
const logoOutDir = path.join(root, 'public/logos')
const manifestPath = path.join(root, 'src/data/imageManifest.ts')

const WIDTHS = [480, 768, 1024, 1536]
const WEBP_QUALITY = 78
const JPEG_QUALITY = 82

await fs.mkdir(outDir, { recursive: true })
await fs.mkdir(logoOutDir, { recursive: true })

const files = (await fs.readdir(srcDir)).filter((f) => /\.(png|jpe?g|webp)$/i.test(f)).sort()
const manifest = {}

for (const file of files) {
  const id = file.replace(/\.[^.]+$/, '')
  const input = sharp(path.join(srcDir, file)).rotate()
  const meta = await input.metadata()
  const { width, height } = meta
  const widths = WIDTHS.filter((w) => w <= width)
  if (!widths.includes(width) && width < 1536) widths.push(width)

  for (const w of widths) {
    await input
      .clone()
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY, effort: 5 })
      .toFile(path.join(outDir, `${id}-${w}.webp`))
  }
  const largest = Math.max(...widths)
  await input
    .clone()
    .resize({ width: largest, withoutEnlargement: true })
    .jpeg({ quality: JPEG_QUALITY, mozjpeg: true, progressive: true })
    .toFile(path.join(outDir, `${id}-${largest}.jpg`))

  manifest[id] = { width, height, widths, fallback: `/images/${id}-${largest}.jpg` }
  console.log(`✓ ${id}  ${width}x${height}  →  ${widths.join('/')}w`)
}

// Open Graph image: 1200x630, centre-weighted crop of the campus gate photograph.
const og = files.includes('careers-hero.png') ? 'careers-hero.png' : files[0]
await sharp(path.join(srcDir, og))
  .resize({ width: 1200, height: 630, fit: 'cover', position: 'centre' })
  .jpeg({ quality: 84, mozjpeg: true })
  .toFile(path.join(outDir, 'og-default.jpg'))
console.log('✓ og-default.jpg 1200x630')

// Logos: optimise and generate icon sizes from the square mark.
const mark = path.join(logoSrcDir, 'nova-mark.png')
const horizontal = path.join(logoSrcDir, 'nova-logo-horizontal.png')

await sharp(mark).resize({ width: 512, height: 512, fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } }).png().toFile(path.join(logoOutDir, 'nova-mark.png'))
await sharp(mark).resize({ width: 512, height: 512, fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } }).webp({ quality: 90 }).toFile(path.join(logoOutDir, 'nova-mark.webp'))
for (const size of [32, 48, 96, 192, 512]) {
  await sharp(mark)
    .resize({ width: size, height: size, fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toFile(path.join(logoOutDir, `icon-${size}.png`))
}
// Apple touch icons must be opaque: paint the mark on a white tile with padding.
await sharp(mark)
  .resize({ width: 150, height: 150, fit: 'contain', background: '#FFFFFF' })
  .extend({ top: 15, bottom: 15, left: 15, right: 15, background: '#FFFFFF' })
  .flatten({ background: '#FFFFFF' })
  .png()
  .toFile(path.join(logoOutDir, 'apple-touch-icon.png'))
await sharp(horizontal).resize({ width: 1200, withoutEnlargement: true }).png({ compressionLevel: 9 }).toFile(path.join(logoOutDir, 'nova-logo-horizontal.png'))
await sharp(horizontal).resize({ width: 1200, withoutEnlargement: true }).webp({ quality: 88 }).toFile(path.join(logoOutDir, 'nova-logo-horizontal.webp'))
// Small horizontal logo for e-mail templates (kept under 40 KB).
await sharp(horizontal).resize({ width: 480 }).png({ compressionLevel: 9, palette: true }).toFile(path.join(logoOutDir, 'nova-logo-email.png'))
console.log('✓ logos + icons')

const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run \`npm run images\` after adding or replacing files in assets/images-source/.

export type ImageVariant = {
  /** Intrinsic width of the master image, in pixels. */
  width: number
  /** Intrinsic height of the master image, in pixels. */
  height: number
  /** Available WebP widths (\`/images/<id>-<w>.webp\`). */
  widths: number[]
  /** JPEG fallback path for browsers without WebP support. */
  fallback: string
}

export const imageManifest: Record<string, ImageVariant> = ${JSON.stringify(manifest, null, 2)}

export const webpSrcSet = (id: string) =>
  imageManifest[id]?.widths.map((w) => \`/images/\${id}-\${w}.webp \${w}w\`).join(', ') ?? ''
`
await fs.writeFile(manifestPath, ts)
console.log(`✓ wrote ${path.relative(root, manifestPath)}`)
