// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run images` after adding or replacing files in assets/images-source/.

export type ImageVariant = {
  /** Intrinsic width of the master image, in pixels. */
  width: number
  /** Intrinsic height of the master image, in pixels. */
  height: number
  /** Available WebP widths (`/images/<id>-<w>.webp`). */
  widths: number[]
  /** JPEG fallback path for browsers without WebP support. */
  fallback: string
}

export const imageManifest: Record<string, ImageVariant> = {
  "careers-hero": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/careers-hero-1536.jpg"
  },
  "civil-construction-hero": {
    "width": 1403,
    "height": 1121,
    "widths": [
      480,
      768,
      1024,
      1403
    ],
    "fallback": "/images/civil-construction-hero-1403.jpg"
  },
  "civil-facility": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/civil-facility-1536.jpg"
  },
  "engineering-fabrication": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/engineering-fabrication-1536.jpg"
  },
  "engineering-hero": {
    "width": 1535,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1535
    ],
    "fallback": "/images/engineering-hero-1535.jpg"
  },
  "future-vision-hub": {
    "width": 1535,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1535
    ],
    "fallback": "/images/future-vision-hub-1535.jpg"
  },
  "healthcare-hero": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/healthcare-hero-1536.jpg"
  },
  "healthcare-quality": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/healthcare-quality-1536.jpg"
  },
  "hemm-hero": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/hemm-hero-1536.jpg"
  },
  "hemm-workshop": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/hemm-workshop-1536.jpg"
  },
  "home-hero": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/home-hero-1536.jpg"
  },
  "skill-development-hero": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/skill-development-hero-1536.jpg"
  },
  "startup-hero": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/startup-hero-1536.jpg"
  },
  "technology-hero": {
    "width": 1536,
    "height": 1024,
    "widths": [
      480,
      768,
      1024,
      1536
    ],
    "fallback": "/images/technology-hero-1536.jpg"
  },
  "who-we-are": {
    "width": 1024,
    "height": 576,
    "widths": [
      480,
      768,
      1024
    ],
    "fallback": "/images/who-we-are-1024.jpg"
  }
}

export const webpSrcSet = (id: string) =>
  imageManifest[id]?.widths.map((w) => `/images/${id}-${w}.webp ${w}w`).join(', ') ?? ''
